version: '3.8'
services:
  web:
    build: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    # command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./app:/app    # Mount local ./app folder to /app inside the container
  test:
    build: .
    container_name: fastapi-tests
    command: pytest
    environment:
      - PYTHONPATH=/app

#networks:
#  frontend_net:
#  backend_net: